### ISSUE TITLE
New Release for TextModels.jl

### ISSUE THREAD

**Issue by AdarshKumar712** [JuliaText/TextModels.jl#28]
Since a lot was updated in the last PR, can we have a new release for the TextModels?
cc @aviks @tejasvaidhyadev

**Comment by sglyon** [comment]
Ping here ! I'm hoping to use this in a course, but the out of date dependency specification is trying to force old versions of Flux.jl that require CuArrays.jl, which has been deprecated.

It results in TextModels.jl being un-installable from a clean environment on apple devices (maybe others ?)

**Comment by aviks** [comment]
Sorry it took so long. Done now. https://github.com/JuliaRegistries/General/pull/49904

If anyone wants to help maintain this library, I'll accept gratefully.
